### ISSUE TITLE
Can't specify a manifests PR for any kubeflow PR #3649

### ISSUE THREAD

**Issue by abcdefgs0324** [abcdefgs0324/test-yaml#62]
there should be a way to specify a manifests PR when a kubeflow PR requires changes in manifests.
Similarly, there should be a way to specify a kubeflow PR from a manifests PR.

jlewi Is there a way to use PULL_PULL_SHA? Right now I'm setting it explicitly in kfctl_go_test.py (see #3639 )

**Comment by jlewi** [comment]
What repo is #3639 in ?

is this an actual question or are you just testing the bot?

**Comment by abcdefgs0324** [comment]
@jlewi I just tested the bot and forgot to remove the tag. Sorry about that.
